"use client";

import {
  Plane,
  Calendar,
  Users,
  CreditCard,
  MapPin,
  BarChart3,
  Ticket,
  FileText,
  Tag,
  MessageSquare,
  Shield,
  Globe,
  Settings,
  Mail,
  TrendingUp,
  Package,
  RefreshCw,
  FileEdit,
  UserCog,
  StoreIcon,
  Folder,
  CalendarDays,
  Cpu,
  Columns,
  Key,
} from "lucide-react";
import { ROLES } from "@/lib/rbac/permissions";

export const adminConfig = {
  header: {
    logo: {
      type: "text" as const,
      text: "The Algoman",
    },
    menuItems: [],
    user: null,
    showSearch: true,
    showNotifications: true,
  },

  sidebar: {
    tabs: [
      {
        id: "dashboard",
        label: "Dashboard",
        icon: <BarChart3 className="h-5 w-5" />,
        href: "/dashboard",
        description: "KPIs, revenue, bookings overview",
        roles: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.MANAGER, ROLES.AGENT],
      },
      {
        id: "assets",
        label: "Asset",
        icon: <Folder className="h-5 w-5" />,
        href: "/assets",
        description: "Manage assets",
        roles: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.MANAGER],
      },
      {
        id: "dailyAsset",
        label: "Daily Asset",
        icon: <CalendarDays className="h-5 w-5" />,
        href: "/daily-asset",
        description: "Daily asset tracking",
        roles: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.MANAGER],
      },
      {
        id: "optionBuffer",
        label: "Option Buffer",
        icon: <Cpu className="h-5 w-5" />,
        href: "/option-buffer",
        description: "Options buffer overview",
        roles: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.MANAGER],
      },
      {
        id: "trades",
        label: "Trades",
        icon: <Columns className="h-5 w-5" />,
        href: "/trades",
        description: "Manage trade history",
        roles: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.MANAGER],
      },
      {
        id: "brokerKeys",
        label: "Broker Keys",
        icon: <Key className="h-5 w-5" />,
        href: "/broker-keys",
        description: "Manage API keys",
        roles: [ROLES.SUPER_ADMIN, ROLES.ADMIN],
      },
      {
        id: "brokers",
        label: "Brokers",
        icon: <StoreIcon className="h-5 w-5" />,
        href: "/brokers",
        description: "View and edit brokers",
        roles: [ROLES.SUPER_ADMIN, ROLES.ADMIN, ROLES.MANAGER, ROLES.AGENT],
      },
      {
        id: "users",
        label: "Users",
        icon: <Users className="h-5 w-5" />,
        href: "/users",
        description: "User management",
        roles: [ROLES.SUPER_ADMIN, ROLES.ADMIN],
      },
    ],
  },
};
